### PR TITLE
Made responsive and background changes

### LINKED ISSUE #17: Making the whole website Responsive-
## I'm submitting a ...

- [X] Bug report
- [X] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

## Current behaviour
In the current situation the website is not fully responsive for that it maybe create a problem for the user who will use the website from other devices.

## What is the motivation / use case for changing the behavior?
I will try to make the whole interface Responsive under GSSOC'24. I will try to make settings part also responsive by changing some required changes in UI. @EternoSeeker will you please assign this problem to me

### PR DESCRIPTION
**Pull request by Pujan-sarkar**
## Description
1. Gradient Background:
   - Changed to linear-gradient(135deg, #ebf2ff 0%, #7582b2 100%)
2. Body Style:
   - Applied the new gradient background.
3. Scrollbar Styles:
   - Customized scrollbar track and thumb colors.
4. Heading Style:
   - Updated color and text-shadow for .heading.
5. Grid Container and Main Grid:
   - Changed border color to use theme's border color.
6. Button Styles:
   - Adjusted button colors, shadows, and hover/active effects.
7. Sidenav Styles:
   - Updated background colors to match the theme.
8. Media Queries:
   - Adjusted element sizes for responsiveness on smaller screens.

What kind of change does this PR introduce? (Bug fix, feature) .

## Related Issue
 Please link to the issue here:  Fixes #17 

## Motivation and Context

The changes were made to enhance the website's aesthetic and user experience by creating a cohesive color scheme that matches the game's theme. This includes a new gradient background, improved readability with better text contrast, smooth transitions for a polished look, custom scrollbars, and optimized responsive design for better functionality on smaller screens. Additionally, updated button styles provide clearer interaction feedback, making the interface more visually appealing and user-friendly.

## Checklist
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

## Screenshots (if necessary):

image_2024-05-18_205642195

Screenshot 2024-05-18 205622

### CODE REVIEW

**Comment by Pujan-sarkar** [comment]
@EternoSeeker please give some reply about my PR .....

**Comment by EternoSeeker** [comment]
@Pujan-sarkar can you keep the icons in a line

**Comment by EternoSeeker** [comment]
It's hard to make it responsive for mobile since I considered desktop first approach

**Comment by Pujan-sarkar** [comment]
@EternoSeeker okay i am trying

**Comment by Pujan-sarkar** [comment]
@EternoSeeker can you check now it is looking good from before , if do the buttons in one line it will be very small so i do that ,please check the pr and give me feedback

**Comment by EternoSeeker** [comment]
It's better now

**Comment by Pujan-sarkar** [comment]
@EternoSeeker can you explain me about the the level lable ?

**Pull request merged**
