### PR TITLE
GridSize changes when applying a preset

### LINKED ISSUE #302: BUG: Preset doesn't work as intended if grid size is changed below 30
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

image

The presets are created to be applied on 30x60 grid or a larger grid
If the user applies presets on a grid of smaller size the presets don't work as intended.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by partha120804**
## Description
When grid sizes are set below 30 the Preset applying was not as expected.
Fixed the bug now applying a preset resets the grid size to 30.

## Related Issue
Closes #302 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by partha120804** [comment]
@EternoSeeker please review this PR

**Comment by EternoSeeker** [comment]
I think we can allow setting presets for sizes more than 30, it's just the smaller sizes that'll cause problems. since some presets would look nice in larger grids
so we should allow for >= 30 but reset for sizes less than 30

**Comment by partha120804** [comment]
Yeah sounds good

**Comment by partha120804** [comment]
@EternoSeeker done

**Pull request merged**
