### PR TITLE
Added Presets, Fixed SHA384 Hash Mismatch

### PR DESCRIPTION
**Pull request by Aryan-Shan**
Fixed SHA384 Hash Mismatch and added Presets

### CODE REVIEW

**Comment by EternoSeeker** [comment]
They look really good @Aryan-Shan , there are some merge conflicts, can you resolve them? I'll merge it. Thank you

**Comment by Aryan-Shan** [comment]
@EternoSeeker  i have resolved the conflicts. Thanks for your feedback

**Comment by EternoSeeker** [comment]
> @EternoSeeker i have resolved the conflicts. Thanks for your feedback

They weren't properly resolved ig
Sorry for troubling, you have the code that worked previously, can you make your changes on the current state of the repository
and maybe create a new PR
The deploy preview shows some flaws, some issue with js I think

**Comment by EternoSeeker** [comment]
@Aryan-Shan your work is good, please look into the conflicts, there are some issues with syncing I think

**Pull request closed without merging**
