### PR TITLE
Added music to the game

### LINKED ISSUE #329: Feat:Adding music to the game
### Describe the feature

Adding a music to the game 

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## Description
Added music to the game And a button for the music

## Related Issue
 closes #329 

## Motivation and Context
To Add music to the game

## How Has This Been Tested?

I have runned the code on my computer

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):

image

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@EternoSeeker  @bubble003 please Review my pull request

**Comment by bubble003** [comment]
@Saipradyumnagoud  code looks fine, but I am unsure whether this feature must be added. @EternoSeeker will update you on that.  Till then maybe you can style it better according to different themes that exist and add padding.

**Comment by Saipradyumnagoud** [comment]
> u can style it better according to different themes that exist and add padding.



> @Saipradyumnagoud code looks fine, but I am unsure whether this feature must be added. @EternoSeeker will update you on that. Till then maybe you can style it better according to different themes that exist and add padding.

yeah sure

**Comment by EternoSeeker** [comment]
Can it be placed in the settings section in side bar

**Comment by Saipradyumnagoud** [comment]
@EternoSeeker You can see now i have added it in the settings section

**Comment by EternoSeeker** [comment]
Screenshot 2024-07-03 222726
You simply added the button, you can nest it under a div, like other elements in the sidebar

**Comment by Saipradyumnagoud** [comment]
> Screenshot 2024-07-03 222726 You simply added the button, you can nest it under a div, like other elements in the sidebar

Yeah sure
i will work on it

**Comment by Saipradyumnagoud** [comment]
@EternoSeeker Please check now i have added div now

**Review by EternoSeeker — APPROVED** [review]

**Comment by EternoSeeker** [comment]
Looks good, thank you

**Pull request merged**
