### PR TITLE
Added animation under issue #47 [GGsoC24]

### PR DESCRIPTION
**Pull request by Harman8815**
## Description
I have enhanced the website by adding animations and making the UI more appealing. Specifically, I changes the UI of old buttons which resulted in a higher contrast and added floating animations to the the heading which make it pops out more. Previously, the Website was too basic and lacked proper taste of animations , but now it stands out and is more visually pleasing.

## Related Issue
The earlier design lacked appeal and genuineness.

## Motivation and Context
These changes aim to make the website cleaner by adding an animation that enhances the overall feel of the design upon reloading.

## How Has This Been Tested?
I have tested this website on my own laptop and it runs well. 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):

https://github.com/EternoSeeker/gameoflife/assets/115714095/dd70ab8e-f697-4710-b04b-c06a209e99e2

- [X] I'm a GSSOC'24 contributor.

### CODE REVIEW

**Comment by EternoSeeker** [comment]
there are few conflicts in html file, please look into it

**Comment by Harman8815** [comment]
I've addressed all the Conflicts in the project. 
Please review the updates and let me know if anything needs to be adjusted. Additionally, could you please add the 'GGsoc' labels to the project? 
I completed this work under the 'GGsoC' issue, which can be found here: [ Issue](https://github.com/EternoSeeker/gameoflife/issues/47).

**Comment by EternoSeeker** [comment]
@Harman8815 contact us and game rules - in the side bar, don't seem to animate

**Comment by Harman8815** [comment]
Those were added later, but I will look into it.

**Comment by EternoSeeker** [comment]
sure

**Pull request closed without merging**
