### PR TITLE
Added a Logo in Documentation form #203

### PR DESCRIPTION
**Pull request by KomalSrivastava**
Added a Logo in Documentation form

## Description
I have added a Logo in Documentation form . This fixes issue number #203 

## Related Issue
I have added a Logo in Documentation form which you can find by name Game.md and logo name is GameOL.png which is in images section. Logo is in transparent and in doc form as per your instructions.

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
Logo img:

image

Documentation Game.md:

Screenshot 2024-07-24 070952

@EternoSeeker I have created fresh fork and then made changes to it as per your instructions . Review it and merge my pull request..  See this issue because it is an old issue you know well , kindly add gssoc and level label in it.

### CODE REVIEW

**Comment by EternoSeeker** [comment]
Screenshot 2024-07-23 221605

**Comment by KomalSrivastava** [comment]
@EternoSeeker I have updated now it is showing?

**Comment by EternoSeeker** [comment]
Looks fine, thank you for contributing

**Comment by KomalSrivastava** [comment]
@EternoSeeker sir its level2 in the Issue.

**Pull request merged**
