### PR TITLE
Added theme and Preset

### PR DESCRIPTION
**Pull request by Bhumika1312**
## Description
This pull request introduces a new preset  "Pentadecathlon" and a new theme "Sunset" to Conway's Game of Life, enhancing the variety of patterns available for users to explore.

## Related Issue
Fixed: #244

## Motivation and Context
By incorporating a wider variety of patterns and themes, we can elevate the game to a whole new level of excitement and engagement.

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
Screenshot 2024-06-13 111057
Screenshot 2024-06-13 105010
Screenshot 2024-06-13 093621

### CODE REVIEW

**Comment by EternoSeeker** [comment]
Screenshot 2024-06-13 135224
Font color of "settings" isn't that vibrant, can you please update it, thank you

**Comment by Bhumika1312** [comment]
Made changes:

image

**Comment by Bhumika1312** [comment]
@EternoSeeker Can you please review it and tell me if there are more changes needed

**Comment by EternoSeeker** [comment]
This looks good. Also you may raise another issue to update the preset and theme in documentation and updating preset in game rules page, thank you

**Pull request merged**
