### PR TITLE
done #207

### PR DESCRIPTION
**Pull request by dnyandeepchute**
## Description
feature

## Motivation and Context
made web site more attractive

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by partha120804** [comment]
The total website has become unresponsive, what did you do bro

**Comment by dnyandeepchute** [comment]
@partha120804 might be due to new feature i will just check.

**Comment by dnyandeepchute** [comment]
@partha120804 its solved, please check now, thank you.

**Comment by partha120804** [comment]
Yeah the page is responsive now but looks like the fork you were working on hasnt been updated from a long time. Try syncing it maybe ?

**Comment by dnyandeepchute** [comment]
@partha120804  ok will do it now.

**Comment by dnyandeepchute** [comment]
@partha120804 worked according to your feedback please check and merge it, loved working on your project, thank you.

**Comment by partha120804** [comment]
Brother, I am not the admin, I am also a contributor like you. I just had some suggestions I gave you.

**Comment by EternoSeeker** [comment]
@dnyandeepchute can you sync it now, since there was a bug which is resolved now. Your changes are really good.

**Comment by dnyandeepchute** [comment]
@EternoSeeker done.

**Comment by EternoSeeker** [comment]
> @EternoSeeker done.

hey, there are still some conflicts that can't be resolved in web editor

**Comment by dnyandeepchute** [comment]
i do it from start.

**Comment by dnyandeepchute** [comment]
@EternoSeeker please check #245, thank you.

**Pull request closed without merging**
