### PR TITLE
Adding a Logo #203

### PR DESCRIPTION
**Pull request by KomalSrivastava**
adding a logo

## Description

it is a feature

## Related Issue

https://github.com/EternoSeeker/gameoflife/issues/203#issuecomment-2168323554

## How Has This Been Tested?

I have added logo in it..

#203  is fixed

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
Screenshot 2024-06-21 210901

### CODE REVIEW

**Comment by KomalSrivastava** [comment]
@EternoSeeker I have added a logo you can check my PR and please add gssoc label and level 2 in it so that it can be counted in the leaderboard.

**Comment by EternoSeeker** [comment]
can you make it PNG with bg transparent, it'll look better

**Comment by KomalSrivastava** [comment]
@EternoSeeker 
Screenshot 2024-06-22 111640

is this ok?

**Comment by EternoSeeker** [comment]
you've decreased opacity, I think

**Comment by KomalSrivastava** [comment]
@EternoSeeker 
Screenshot 2024-06-22 194348

is this ok?

**Comment by EternoSeeker** [comment]
there is some problem with deploy preview

**Comment by EternoSeeker** [comment]
Screenshot 2024-06-22 213446
You didn't make it transparent, also the sidebar shouldn't be that close to the grid

**Comment by EternoSeeker** [comment]
hey there, you can add the logo to documentation for now.
we can add it to the site later.

**Comment by KomalSrivastava** [comment]
@EternoSeeker ok Sir I'll add the logo to documentation for now. It will be done by tomorrow.

**Comment by KomalSrivastava** [comment]
@EternoSeeker I have kept the img=logo in GameLogo folder . Kindly merge my pull request and add GSSoC and level label in issue #203  and pull request #307

**Comment by EternoSeeker** [comment]
there are few code conflicts here. I think it would be better to create a new pr and simply put the logo in documentation

**Comment by KomalSrivastava** [comment]
@EternoSeeker  I have added  logo in documentation named GameLogo.md . And as you can see all the conflicts is resolved .

**Comment by KomalSrivastava** [comment]
@EternoSeeker I have added the logo in documentation named GameLogo.md.

**Pull request closed without merging**
