### PR TITLE
Edit : Added the play button images and linked these files in html file

### PR DESCRIPTION
**Pull request by CoderGirl2844**
solved issue no. #332

### CODE REVIEW

**Comment by partha120804** [comment]
Couldn't you have used the svg files inline 🤔

Wouldn't that be more efficient ?

**Comment by CoderGirl2844** [comment]
Sir the svg files which were mentioned in the code earlier were deleted from images section..So I uploaded new png files and updated html file accordingly..

**Comment by EternoSeeker** [comment]
@CoderGirl2844 you didn't seem to resize them

**Comment by CoderGirl2844** [comment]
@EternoSeeker ok sir I will resize then

**Comment by EternoSeeker** [comment]
looks fine now, thank you

**Pull request merged**
