### PR TITLE
To solve the theme issue

### PR DESCRIPTION
**Pull request by Janani-m17**
The issue I have raised was if the user choose the theme from colors such as red, blue it is working fine both the background and grid color are changing. But if the user chooses the gradient theme at first and then switch to colors only the grid color is changing, background remains static. But the background should change accordingly. In my code I have updated the bootstrap and done changes in app.js in function select theme to update the background accordingly.

## Description

Updated bootstrap.
selectTheme function is updated in which if the use chooses gradient first it will give a gradient background then if user change to any solid color the background will be updated to that particular color.

I have fixed the bug in Theme selection.

## Motivation and Context

As UI brings a complete experience of the application or website, In this project solving this issue will provide smooth experience and user can explore wide range of themes in the website while playing the game.

## How Has This Been Tested?

I had the run the project using live server then first choose theme using gradient after that choose any solid color it will change accordingly.

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
image

https://deploy-preview-116--eternalgameoflife.netlify.app/

@EternoSeeker

### CODE REVIEW

**Comment by EternoSeeker** [comment]
@Janani-m17 thank you for fixing it.
why there are "1." before the options ? could you please look into it, thank you

**Comment by Janani-m17** [comment]
Thank you for reviewing sir. Now I will work on that 1 displaying issue.

@EternoSeeker

**Comment by Janani-m17** [comment]
I have solved the 1 displaying issue by making some changes in index.html file.
image
@EternoSeeker

**Comment by EternoSeeker** [comment]
> I have solved the 1 displaying issue by making some changes in index.html file. image @EternoSeeker

@Janani-m17 it's still visible for presets, please look into it, thank you

**Comment by Janani-m17** [comment]
I have updated the code sir. @EternoSeeker

**Comment by EternoSeeker** [comment]
Thank you for solving the issue

**Comment by Janani-m17** [comment]
Thank you sir for your valuable feedbacks.
@EternoSeeker

**Pull request merged**
