### PR TITLE
Improved isEmpty from O(mn) to O(1)

### PR DESCRIPTION
**Pull request by Dirus007**
## Description

Changed the isalive() function in app.js

Improved complexity by just storing the count of alive cells. This variable can help in future other functions.
## Motivation and Context

From iterating over array we go to a constant function. Saves a lot of time.

## How Has This Been Tested?

Checked nearly all the functionalities in browser.

Yes, we now have to update this variable in other parts of app.js

## Checklist
- [Yes ] I have performed a self-review of my code
- [ Yes] I have commented my code, particularly in hard-to-understand areas
- [ Yes] I have made corresponding changes to the documentation
- [ Yes] My changes generate no new warnings

### CODE REVIEW

**Comment by EternoSeeker** [comment]
are you participating in gssoc ?

**Review by EternoSeeker — APPROVED** [review]

**Comment by Dirus007** [comment]
> are you participating in gssoc ?

Yes

**Comment by EternoSeeker** [comment]
You didn't test it well I think

**Comment by Dirus007** [comment]
> You didn't test it well I think

Yeah, just saw, preset function was not working well because missed on updating alive count there.

**Pull request merged**
