### PR TITLE
Adding Chatbot to website

### LINKED ISSUE #389: Feat: Adding Chatbot to website
### Describe the feature

@EternoSeeker I want to add chatbot to the website. Kindly assign this issue to me.

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Description

@EternoSeeker I have added the Chatbot to the website. Kindly review this.

## Related Issue

Fixes #389 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):

Screenshot 2024-07-16 001942

### CODE REVIEW

**Comment by EternoSeeker** [comment]
chatbot didn't assist me with anything
can you tell what use case does it have, cause it doesn't seem to say anything related to the game or other stuff

**Comment by Ojas-Arora** [comment]
@EternoSeeker Sir this chatbot is mainly for answering question related to the Feedback,Faq or mainly about the description provided in the repo or website.

**Comment by EternoSeeker** [comment]
> @EternoSeeker Sir this chatbot is mainly for answering question related to the Feedback or the Faqs and description as its mainly a business specified chatbot for the Gssoc'24

please attach some ss where it answers such questions, thank you

**Comment by Ojas-Arora** [comment]
Screenshot 2024-07-23 223335
Screenshot 2024-07-23 223532
@EternoSeeker Sir these are the 2 screenshots that I have taken from my local.

**Comment by EternoSeeker** [comment]
Screenshot 2024-07-26 221520

**Comment by Ojas-Arora** [comment]
@EternoSeeker Sir I think so Actualy I have the main registered email for this that's why it's showing me the answer

**Comment by EternoSeeker** [comment]
I think it should be able to answer basic questions without login,
since our project doesn't need to be logged in

**Comment by Ojas-Arora** [comment]
Sir there is nothing required for login it's just the registered email for the chatbot for answers

**Comment by Ojas-Arora** [comment]
@EternoSeeker Sir Kindly please tell what to do now as Gssoc is about to end in 2 days.

**Comment by Ojas-Arora** [comment]
@EternoSeeker Sir Kindly please see

**Comment by EternoSeeker** [comment]
there are some conflicts there, could you resolve them

**Comment by Ojas-Arora** [comment]
@EternoSeeker ok

**Comment by Ojas-Arora** [comment]
@EternoSeeker Done

**Comment by EternoSeeker** [comment]
It made it worse ig, in the deploy preview.
um I think a fresh fork would be the solution, you can put your code again and create a PR.

**Comment by Ojas-Arora** [comment]
@EternoSeeker ok

**Pull request closed without merging**
