### PR TITLE
Added aria labels to the buttons

### PR DESCRIPTION
**Pull request by anythingkartik**
Description
Added aria labels the the buttons

What problem does it solve? 
aria labels to the control buttons will greatly enhance the accessibility of the Conway's Game of Life webpage. These labels provide clear descriptions of each button's functionality

### CODE REVIEW

**Comment by anythingkartik** [comment]
I have added the labels 
This is my first ever commit and first time using PR, Thank you for giving me this opportunity
Let me know of any other level 1 issues.

**Comment by EternoSeeker** [comment]
> I have added the labels This is my first ever commit and first time using PR, Thank you for giving me this opportunity Let me know of any other level 1 issues.

The HTML file is modified due to other PRs, hence there are merge conflicts, please pull those changes and make the necessary changes, thank you.

**Comment by anythingkartik** [comment]
> > I have added the labels This is my first ever commit and first time using PR, Thank you for giving me this opportunity Let me know of any other level 1 issues.
> 
> The HTML file is modified due to other PRs, hence there are merge conflicts, please pull those changes and make the necessary changes, thank you.

Hello @EternoSeeker 
Can you elaborate please, like do i have to do it again or like you meant something else ...

**Comment by anythingkartik** [comment]
> > I have added the labels This is my first ever commit and first time using PR, Thank you for giving me this opportunity Let me know of any other level 1 issues.
> 
> The HTML file is modified due to other PRs, hence there are merge conflicts, please pull those changes and make the necessary changes, thank you.

I really wanted to pull my first pr and i will solve the issue again

**Comment by EternoSeeker** [comment]
Yea, thank you for solving the conflicts, I can merge now

**Comment by anythingkartik** [comment]
Hi @EternoSeeker you assigned me the to add aria labels again?

**Pull request merged**
