### PR TITLE
error 404

### PR DESCRIPTION
**Pull request by taneeshaa15**
Error page:
game

Hi @EternoSeeker  ,
I hope you're doing well. I've addressed the issue #252  and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

### CODE REVIEW

**Comment by EternoSeeker** [comment]
The directory name, it's good to avoid space bar in directory names

**Comment by taneeshaa15** [comment]
Updated, Please review.

**Comment by EternoSeeker** [comment]
go to home shall redirect to game page right

**Comment by taneeshaa15** [comment]
@EternoSeeker Tell the name of the file which you want me to redirect.

**Comment by EternoSeeker** [comment]
https://github.com/EternoSeeker/gameoflife/blob/main/index.html

**Comment by taneeshaa15** [comment]
@EternoSeeker Please review it now.

**Comment by EternoSeeker** [comment]
only the link should have pointed to the page, you changed the whole page

**Comment by taneeshaa15** [comment]
@EternoSeeker It redirects itself to the index.html page after a certain time.
If you want I can change that to manual redirection and will remove the time limit.

**Comment by EternoSeeker** [comment]
> @EternoSeeker It redirects itself to the index.html page after a certain time. If you want I can change that to manual redirection and will remove the time limit.

Please see the deploy preview, and the index.html in your fork doesn't exist in the main directory, you replaced the file, than pointing to it

**Pull request closed without merging**
