### PR TITLE
Placed the music button with a check box option in the general settings

### LINKED ISSUE #347: Feat: Music button to be listed under settings with grid and wrap options
### Describe the feature

Add music button within the setting with wrap and grid buttons with a suitable checkbox/slider button design

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by partha120804**
## Description
The music button is moved to a suitable spot

## Related Issue
fixes #347 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):

image

UPDATE :
corrected the code such that the keyboard shortcuts also check uncheck the checkboxes.

### CODE REVIEW

**Comment by partha120804** [comment]
@EternoSeeker this PR will create conflicts after my previous PR is merged so I will resolve conflicts and open it after that PR is merged.

**Comment by EternoSeeker** [comment]
okay

**Comment by partha120804** [comment]
@EternoSeeker resolved all the conflicts now the PR is ready to be merged.

**Comment by EternoSeeker** [comment]
it's good, although the controls can be given some bottom margin

**Comment by partha120804** [comment]
hello, @EternoSeeker please check the recent PR

image

I have added some border to the other settings container

**Comment by EternoSeeker** [comment]
I mean the game controls look like they are stick to bottom, hence some margin there

**Comment by partha120804** [comment]
@EternoSeeker I a screenshot maybe, i am not seeing any such issues 

image

**Comment by EternoSeeker** [comment]
oh, alright

**Pull request merged**
