### PR TITLE
Fix #111 : Enhance UI

### LINKED ISSUE #111: Feat: To Improve UI and UX
### Describe the feature

1.) Tooltips for Controls:

- Brief messages that appear when hovering over controls to explain their functionality.

2.) Help Section:

- A dedicated section that provides detailed instructions on how to use the application.

3.) Reset Button:

- A button that resets all settings and clears the grid.

### Add ScreenShots

Screenshot (50)_LI

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Swapnilden**
## Description
This PR adds tooltips to the control buttons on the grid interface, providing users with additional context and information about each button's functionality. The tooltips appear with a slight delay when the user hovers over the buttons, enhancing the user experience.

## Related Issue
Fixes: #111

## Motivation and Context
Tooltips help users understand the purpose of buttons and controls without requiring them to refer to external documentation. This enhancement improves the usability of the interface, especially for new users who may not be familiar with all the controls.

## How Has This Been Tested?

- Manually tested on desktop browsers (Chrome, Firefox, Safari) to ensure tooltips appear correctly on hover.
- Verified that the tooltips disappear when the mouse leaves the button.
- Ensured that the tooltips do not obstruct other elements and are displayed above all other elements.
- Checked the functionality of all buttons to confirm that adding tooltips did not interfere with their existing behavior.

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
Screenshot (53)

### CODE REVIEW

**Comment by EternoSeeker** [comment]
this is really good.
however @Swapnilden 
the tips are clickable just like the button, they can go away once the mouse is not hovering over them directly
can you look into it, thank you

**Comment by Swapnilden** [comment]
Okay i will

**Comment by Swapnilden** [comment]
@EternoSeeker Now, you can check

**Comment by EternoSeeker** [comment]
thank you @Swapnilden

**Comment by Swapnilden** [comment]
My pleasure

**Pull request merged**
