### PR TITLE
Added gradient theme button 

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## Description
I've implemented a new feature that allows users to select colors for their gradient and choose the direction of the gradient.

## How Has This Been Tested?
Running the code multiple times on my local device to ensure its functionality.

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots 

image

image

image

image

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
Resolves issue #19

**Comment by EternoSeeker** [comment]
@aditya-bhaumik I think you'll need to pull the changes caused by other PRs, and resolve the conflicts. Thank you.
The gradient themes look really cool !

**Comment by aditya-bhaumik** [comment]
@EternoSeeker  I have resolved the conflict can you please try merging now.

**Comment by EternoSeeker** [comment]
Thank you

**Pull request merged**
