### PR TITLE
Introduction series

### PR DESCRIPTION
**Pull request by Jasleen1210**
Issue #349 

## Related Issue
#349 

## Motivation and Context
Introduces user to the controls of the game

## How Has This Been Tested?
Run on my browser

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Jasleen1210** [comment]
https://github.com/user-attachments/assets/786b0462-3335-4d95-81d2-ece823cc6da8

[sped up video]

**Comment by EternoSeeker** [comment]
This is amazing, although there are some things I need to highlight
first - play/pause button doesn't point to right button
Screenshot 2024-07-14 200440
second - when I click on gamerules page for example, and come back to this main page, I am not supposed to go through all those steps again right
so what you can do is only do it once per session, I think that would be possible

**Comment by Jasleen1210** [comment]
@EternoSeeker Fixed the second issue, working on the first part but even with multiple media queries the alignment get skewed at one point or another, any suggestions for it?

**Comment by EternoSeeker** [comment]
Shall I merge your changes though, the walkthrough once per session works fine

**Comment by Jasleen1210** [comment]
> Shall I merge your changes though, the walkthrough once per session works fine

@EternoSeeker Please do

**Pull request merged**
