### PR TITLE
Feat: Fixed the bottom bar buttons so that their colors change with theme theme.

### LINKED ISSUE #262: Feat: Redesign the whole bottom bar buttons
### Describe the feature

I want to work on the bottom bar to make it more uniform and appealing

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by partha120804**
Changed the buttons' svg files.
Added the svg files inside the html file so that they can be easily accessed in style and javascript and used inline svg features to change the fill colour of the button with according to the theme so those buttons dont look out of the place.

Before those buttons were pure black in colour and hence they seemed out of place on the page.

## Issue Faced :
Before this, the Play and Pause toggle is done by changing the source of img file, which can't be done using svg files.
So it was hard to use the same for inline svg and hence the colours couldn't be changed.

## Solution :
I defined both svg paths in a single svg block under the Play Pause Icon and changed the fill colour of Pause Icon to transparent by default.
Then a function "togglePlayPause" is defined which changes the fill colours of the svg paths.
When Pause button is activated -> Fill color of Play icon is set to transparent and the Pause icon is filled with active font color
and vice versa when Play button is activated.
And no a single inline svg can take the shape of both buttons as and when needed.

## Related Issue :
Closes #262 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by partha120804** [comment]
## Issue Faced :
Before this, the Play and Pause toggle is done by changing the source of img file, which can't be done using svg files.
So it was hard to use the same for inline svg and hence the colours couldn't be changed.

## Solution :
I defined both svg paths in a single svg block under the Play Pause Icon and changed the fill colour of Pause Icon to transparent by default.
Then a function "togglePlayPause" is defined which changes the fill colours of the svg paths.
When Pause button is activated -> Fill color of Play icon is set to transparent and the Pause icon is filled with active font color
and vice versa when Play button is activated.
And no a single inline svg can take the shape of both buttons as and when needed.

**Comment by EternoSeeker** [comment]
when there's a pattern that eventually ends up in empty grid, e.g just one cell is selected as alive and it'll vanish
in this case the pause button still is visible, even after clicking on clear button
please look into it

**Comment by partha120804** [comment]
@EternoSeeker 
Please check now, I have resolved the issue

**Comment by EternoSeeker** [comment]
Great, thank you

**Pull request merged**
