### PR TITLE
created a page for game rules

### PR DESCRIPTION
**Pull request by syannam-12**
## Checklist
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by EternoSeeker** [comment]
You can keep the about section as it is, since it redirects here to documentation
Also make sure it styles well along the other elements in settings

**Comment by syannam-12** [comment]
I am sorry but I did not understand what you were trying to say. Did you
perhaps means that there's no need for a new game rules page and only work
on the styling of the game?

**Comment by EternoSeeker** [comment]
@syannam-12 I just mean that don't remove previous section and keep your section styling consistent with other elements in settings

**Comment by syannam-12** [comment]
Ok, thanks for the clarification.

**Pull request closed without merging**
