### PR TITLE
Added social media icons

### PR DESCRIPTION
**Pull request by JagjeetChauhan**
## Description
Added social media icons in the sidebar of the setting

## Related Issue
<#335>

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
image

### CODE REVIEW

**Comment by EternoSeeker** [comment]
It tries to underline the github icon, you can use a simple effect there.
also there seem to be some conflicts with index HTML file, please resolve it, thank you.

**Comment by JagjeetChauhan** [comment]
@EternoSeeker I have resolved all the conflicts

**Comment by JagjeetChauhan** [comment]
I have also removed the underline effect
image

**Comment by EternoSeeker** [comment]
Looks great, thank you !

**Comment by EternoSeeker** [comment]
@JagjeetChauhan please submit pr again, I will have to revert this

**Comment by JagjeetChauhan** [comment]
Ok, I will make a PR again.

**Pull request merged**
