### PR TITLE
SOLVES: Initial cell toggle bug

### LINKED ISSUE #216: BUG: Fix event listeners on cells
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

User should be able to select cells before game starts, and not after the simulation has started.
User will be able to select cells as alive only after the grid is cleared 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by partha120804**
A second grid was created under the initial grid when the page loads.

## Description
- Now the user should be able to select cells before game starts, and not after the simulation has started.
- Now the user will be able to select cells as alive only after the grid is cleared
It is a bug fix.

## Related Issue
BUG: Initial Cell Toggling Issue - It closes #216 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by partha120804** [comment]
@EternoSeeker Sorry for so many commits, I think I did something wrong in the fork so its showing my previously merged commits again in this PR but merging this PR will not cause any changes to the previous code.

**Comment by EternoSeeker** [comment]
your previous PR, seems to have solved the event listener bug too, can you just check it once

**Comment by partha120804** [comment]
That PR only solves the initial grid formation issue and the initial cell toggle at the starting, but after clicking random or animate option it doesnt let the user to toggle the cell.

But this PR focuses on initializing the grid everytime, so the toggling still works, even after random and animate options are used.

**Comment by EternoSeeker** [comment]
Alright

**Comment by EternoSeeker** [comment]
There are still some issues with event listeners, When we load from presets and play, and clear the grid, later it doesn't toggle to alive state

**Comment by partha120804** [comment]
nothing seems to work I will try to push another branch with less commits for this issue.

**Pull request closed without merging**
