### PR TITLE
Emoji Review Section Added 

### PR DESCRIPTION
**Pull request by Damini2004**
## Description
Emoji Review Section Added 

## Related Issue
#379 

## Motivation and Context
Emoji Review Section Added 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):

image

Can you increase the level.

### CODE REVIEW

**Comment by EternoSeeker** [comment]
back button goes above the screen, could you fix it

**Comment by Damini2004** [comment]
@bubble003 @EternoSeeker Ok sir i will fixed it.But first review the PR and merge it as gssoc is ending soon.

**Comment by Damini2004** [comment]
@EternoSeeker Fixed the changes
KInldy increase the level.

**Comment by EternoSeeker** [comment]
Thank you for contributing

**Pull request merged**
