### PR TITLE
star added in feedback form

### PR DESCRIPTION
**Pull request by heli0707**
## Description
A star rating system has been added to the feedback form, allowing users to rate their experience from 1 to 5 stars. The stars are styled with CSS, changing color on hover and selection to provide an interactive and modern visual feedback element.

## Related Issue
UI related issue 
#353 

## How Has This Been Tested?
I have tested it on my own.

## Checklist
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

## Screenshots (if necessary):
feedback

### CODE REVIEW

**Comment by bubble003** [comment]
@heli0707 I think it should be reversed, generally reviews stars increases Left to Right & for now, 2nd Left Star  => 4 Star whereas it should be 2 Star.

**Comment by heli0707** [comment]
image

change done

**Comment by heli0707** [comment]
@bubble003 
review and merge it !

**Comment by EternoSeeker** [comment]
there are some conflicts in the css file, please resolve them, thank you

**Comment by heli0707** [comment]
@EternoSeeker 
conflict resolved

**Comment by EternoSeeker** [comment]
That looks fine, thank you for contributing

**Pull request merged**
