### PR TITLE
fix music hover and icons toggle

### LINKED ISSUE #348: BUG: Music ON/OFF button not have hover effects like other options
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

image
Other options have color change hover effects.
But MUSIC ON/OFF not have that hover effect
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by zalabhavy**
## Description

Added Hover effects like other options.
Add Toggling in Music icons add new icons that show music on/music off.

## Related Issue

BUG
Fixes #348

## Motivation and Context

Make it perfect.

## How Has This Been Tested?

Self test by run.

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):

image

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@EternoSeeker Please check it and merge !

**Thank You  !**

**Comment by EternoSeeker** [comment]
the music is on by default, we can keep it off in the beginning then users can turn it on if they want.  I think that will be better

**Comment by zalabhavy** [comment]
@EternoSeeker @bubble003 Changes  Done !

Initially Music Off then user can make it Music On

image

image

**Thank You !**

**Comment by zalabhavy** [comment]
@EternoSeeker Please check it and merge !

**Thank you !**

**Comment by EternoSeeker** [comment]
Works well, thank you

**Comment by zalabhavy** [comment]
@EternoSeeker Thanks 🙏

Please also merge #376

**Pull request merged**
