### PR TITLE
Back button

### PR DESCRIPTION
**Pull request by AnanyaJain25**
## Description

Adding Home icon and Back to home button in Game Rules Page #149

## Motivation and Context

UI was missing back to home button once user goes to gamerules page. 

## How Has This Been Tested?

Changes can be directly seen on browser.

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
Screenshot 2024-05-30 102737
Screenshot 2024-05-30 102753

### CODE REVIEW

**Comment by adityas-github** [comment]
Hey you can add home icon to top left corner as it provides better user experience.

**Comment by AnanyaJain25** [comment]
> Hey you can add home icon to left corner as it provides better user experience.

sure sir

**Comment by AnanyaJain25** [comment]
Screenshot 2024-05-30 175757

**Comment by EternoSeeker** [comment]
@AnanyaJain25 yes it's fine, can you please look into the conflicts, then I can merge, thank you

**Review by EternoSeeker — APPROVED** [review]

**Comment by EternoSeeker** [comment]
thank you @AnanyaJain25

**Pull request merged**
