### PR TITLE
Change Grid Size

### PR DESCRIPTION
**Pull request by TiwariRahul16**
## Description
This functionality allow user to change size of grid by changing the height of grid

## issue

#103 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
change grid

### CODE REVIEW

**Review by EternoSeeker — CHANGES_REQUESTED** [review]
Initializegrid function can be called in changeGridSize right
also when we change grid size, it takes huge space that doesn't fit well with other components
Screenshot 2024-05-31 200828
the min height and min width here are specified for that purpose
So that even though we change grid size, the dimensions of each cell get reduced to adjust with the main-grid height and width
```js
gridContainer.style.gridTemplateRows = `repeat(${HEIGHT}, calc((100%) / ${HEIGHT}))`;
gridContainer.style.gridTemplateColumns = `repeat(${WIDTH}, calc((100%) / ${WIDTH}))`;
```
the above code ensures that.
Overall your code can be much less redundant
please look into it

**Comment by EternoSeeker** [comment]
@TiwariRahul16

**Comment by TiwariRahul16** [comment]
> Initializegrid function can be called in changeGridSize right also when we change grid size, it takes huge space that doesn't fit well with other components Screenshot 2024-05-31 200828 the min height and min width here are specified for that purpose So that even though we change grid size, the dimensions of each cell get reduced to adjust with the main-grid height and width
> 
> ```js
> gridContainer.style.gridTemplateRows = `repeat(${HEIGHT}, calc((100%) / ${HEIGHT}))`;
> gridContainer.style.gridTemplateColumns = `repeat(${WIDTH}, calc((100%) / ${WIDTH}))`;
> ```
> 
> the above code ensures that. Overall your code can be much less redundant please look into it

When we increase the grid height the size of grid increases and all other component do not fit well
but if we maintain the main-grid height and width by reducing dimensions of each cell 
The user experience is not good. because every cell is not clearly visible.
To make better user experiences, i have fixed the code so that user can enter the height of grid in between 0 to 40.

grid2

grid1

**Comment by EternoSeeker** [comment]
> > Initializegrid function can be called in changeGridSize right also when we change grid size, it takes huge space that doesn't fit well with other components Screenshot 2024-05-31 200828 the min height and min width here are specified for that purpose So that even though we change grid size, the dimensions of each cell get reduced to adjust with the main-grid height and width
> > ```js
> > gridContainer.style.gridTemplateRows = `repeat(${HEIGHT}, calc((100%) / ${HEIGHT}))`;
> > gridContainer.style.gridTemplateColumns = `repeat(${WIDTH}, calc((100%) / ${WIDTH}))`;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the above code ensures that. Overall your code can be much less redundant please look into it
> 
> When we increase the grid height the size of grid increases and all other component do not fit well but if we maintain the main-grid height and width by reducing dimensions of each cell The user experience is not good. because every cell is not clearly visible. To make better user experiences, i have fixed the code so that user can enter the height of grid in between 0 to 40.
> 
> grid2
> 
> grid1
I was trying to say that it shouldn't go out of place when we increase grid size
hence I want it to be static sized, the cell height and width gets adjusted when height is 1/2 of width
let me know when you make the changes

**Comment by TiwariRahul16** [comment]
below the main grid there are cells to adjust the main grid height and width when size changes

**Comment by EternoSeeker** [comment]
Excellent it works fine, just fix the initial rendering

**Comment by TiwariRahul16** [comment]
Hii @EternoSeeker 
can you please do some favor for me(it will help me).
please merge this PR and assign me in issue number #63,
so In issue 63 i can make final PR immediately.
Please......................

**Comment by EternoSeeker** [comment]
okay @TiwariRahul16 . please make sure you fix the issue

**Pull request merged**
