### PR TITLE
Fixed cursor pointer when hover on theme color text  ( #80 )

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
## Description

I did some changes in the index.html and css file for adding the hover feature and removing the cursor:pointer for the whole div .

## Motivation and Context
Before this pr when user is hovering theme div then the pointer is converted to cursor the showing like that this is a button but actually this was a div and on clicking nothing happens .

## Checklist
- [x] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
Before :

https://github.com/EternoSeeker/gameoflife/assets/118350936/836ae2c7-7a2e-4be8-aa36-d05f764d440f

After ;

https://github.com/EternoSeeker/gameoflife/assets/118350936/2fc7212b-3391-4cc2-b012-333d54728d9a

### CODE REVIEW

**Comment by EternoSeeker** [comment]
there are some conflicts with css file, could you please fix them, thank you

**Comment by Ayushmaanagarwal1211** [comment]
Can you please check again

**Comment by Ayushmaanagarwal1211** [comment]
I also fixed the issue no. #79 for the dark neon color the buttons with different colors will be shown

**Comment by EternoSeeker** [comment]
Works fine, thank you

**Pull request merged**
