### PR TITLE
Improved Tool-tips

### PR DESCRIPTION
**Pull request by VijaySamant4368**
## Description

I made the tooltips to display over each button their respective function. I also made it so that when a user enters some value in Grid Height, the tool-tip above 'Apply' button changes between 'Invalid Grid Height' and 'Apply Grid Height'

## Related Issue
#317 

## Motivation and Context
For better User Experience

## How Has This Been Tested?
The rest of the tool-tips can be easily checked, but the tooltip over Apply button works after user presses 'Enter' after entering the required value.

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by partha120804** [comment]
Hey, please check js/speed.js, there's a code that changes the tool tip when max/min speed is achieved,

Link it to your new tooltips 😄

**Comment by EternoSeeker** [comment]
yes

**Comment by VijaySamant4368** [comment]
> yes

Can you please tell me what exactly do I have to do?

**Comment by EternoSeeker** [comment]
Alright, this looks fine, thank you.

**Pull request merged**
