### PR TITLE
Overlap of button solved

### PR DESCRIPTION
**Pull request by zalabhavy**
## Description
Just added margins so button not overlap to other.

## Related Issue
issue no #299

## How Has This Been Tested?
Self testing 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):
image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@EternoSeeker Please check it and merge !

**Comment by EternoSeeker** [comment]
why in px, use some relative unit

**Comment by zalabhavy** [comment]
@EternoSeeker What are you mean ? please explain i can't understand.

**Comment by EternoSeeker** [comment]
px is an absolute unit (always be the same size.). It would help if you preferred using relative units like rem, em, etc

**Comment by zalabhavy** [comment]
@EternoSeeker I have updated it with rem.

image

@EternoSeeker Thank you for sharing knowledge with me ! I have no idea about that difference.

**Comment by partha120804** [comment]
Basically when you use px the size remains same on all screens,
But when you use rem/em, the size changes with according to the screen size, so the button size depends relative to the size of device ( pc-big/tablet-medium/phone-small)

**Comment by EternoSeeker** [comment]
looks fine, thank you @zalabhavy

**Pull request merged**
