### PR TITLE
Modified  the cursor

### PR DESCRIPTION
**Pull request by Ramben0909**
## Modified the cursor

I have updated the js for the cursor so that when it goes out the main-gird the color drop disappears 

 

## Motivation and Context
    The change makes the game looks better it portrays that the cursor is active for gameplay on over the grid  

## How Has This Been Tested?
 I have run the code on my system

## Checklist
-  I have performed a self-review of my code
-   I have commented my code, particularly in hard-to-understand areas
-   I have made corresponding changes to the documentation
-   My changes generate no new warnings

## Screenshots (if necessary):
Screenshot 2024-07-02 182245

solved #319 
hey @EternoSeeker please review it

### CODE REVIEW

**Comment by Ramben0909** [comment]
solved issue #339 
sorry for being late 
hey @EternoSeeker please review it

**Comment by EternoSeeker** [comment]
when cursor moves to the right half of the grid, it doesn't seem to show it

**Comment by Ramben0909** [comment]
checking

**Comment by Ramben0909** [comment]
I have solved this issue and added new pull request please check

**Comment by EternoSeeker** [comment]
there are some conflicts with the html file, please look into it

**Comment by Ramben0909** [comment]
> there are some conflicts with the html file, please look into it

the html conflicts are already there before doing any modifications of mine my code doesn't add any new conflicts it shows the same conflicts that exists already 
before adding any code of mine 
Screenshot 2024-07-07 232140
after adding code of mine 
 
Screenshot 2024-07-07 232900

please review it the conflicts are not because of my code, and for which part is it showing I could not understand

**Comment by EternoSeeker** [comment]
no conflicts now, but please fix the cursor, it vanishes in the right half of the grid

**Comment by Ramben0909** [comment]
> no conflicts now, but please fix the cursor, it vanishes in the right half of the grid

check my 2nd commit there I have fixed this issue

**Comment by EternoSeeker** [comment]
It doesn't reflect in the deploy preview though

**Comment by EternoSeeker** [comment]
It'll be safe to close this now.

**Pull request closed without merging**
