### PR TITLE
Grid Size Fix

### PR DESCRIPTION
**Pull request by TiwariRahul16**
## Description

fix all issues related to change grid size

## Related Issue

#63 
 #195 
 #193

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):

gridsize

responsive

### CODE REVIEW

**Comment by TiwariRahul16** [comment]
Finally Done

**Comment by TiwariRahul16** [comment]
Hii @EternoSeeker 
can you assign me 193 and 195 with suitable labels before merging this PR.
please....

**Comment by shreyash3087** [comment]
@TiwariRahul16 Just a suggestion - the max and min grid issue is still there,if i type in 1000 in the grid height,it still crashes the site,you should fix this in this pr

**Comment by EternoSeeker** [comment]
Screenshot 2024-06-05 102956
Upper title can be adjusted better

**Comment by TiwariRahul16** [comment]
> @TiwariRahul16 Just a suggestion - the max and min grid issue is still there,if i type in 1000 in the grid height,it still crashes the site,you should fix this in this pr

I have already informed you about this problem and solution in PR #168.
Because the cells are created in loops, when we increase the height about certain limit the loops takes time and sometimes when  the height is to large it crashes the website.

Solution:  i have only one solution we can fix the upper limit of height.( i recommend the max height should be 250 ).

See the ScreenShots (height and Grid looks. because the cells are not clearly visible after some height ).

im1

im2

m3

im4

**Comment by TiwariRahul16** [comment]
> Screenshot 2024-06-05 102956 Upper title can be adjusted better

its a browser fault. it looks different in different browser.
But i have fixed it for all browser

**Comment by EternoSeeker** [comment]
> > Screenshot 2024-06-05 102956 Upper title can be adjusted better
> 
> its a browser fault. it looks different in different browser. But i have fixed it for all browser

I suggest reducing it's bottom margin little bit, it'll be fine for all browsers then

**Comment by TiwariRahul16** [comment]
> > > Screenshot 2024-06-05 102956 Upper title can be adjusted better
> > 
> > 
> > its a browser fault. it looks different in different browser. But i have fixed it for all browser
> 
> I suggest reducing it's bottom margin little bit, it'll be fine for all browsers then

Yes Done

**Comment by EternoSeeker** [comment]
Thank you @TiwariRahul16 , excellent work

**Comment by EternoSeeker** [comment]
@TiwariRahul16 I had to revert it, because it messes up with the previous code which isn't updated in this branch
can you please look into it

**Pull request merged**
