### PR TITLE
Fix: The weird effect in mobile view

### PR DESCRIPTION
**Pull request by arpy8**
Added background styling to ensure that the background image covers the entire screen without repeating.

## Description

changes made:

image

## Related Issue
#213 

## How Has This Been Tested?
Has been tested locally 

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):

| before                                                                                               | after                                                                                                |
|------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------|
|  |  |

### CODE REVIEW

**Comment by partha120804** [comment]
closes #213

**Comment by arpy8** [comment]
@partha120804 done

**Comment by EternoSeeker** [comment]
It's taking full width now, and close button not visible when it takes full width

**Comment by arpy8** [comment]
Hi @EternoSeeker, can you tell if it's visible now?

**Comment by EternoSeeker** [comment]
can you sync your fork, because there are some changes merged in the project

**Comment by arpy8** [comment]
I've opened a new pr (#243) with no merged conflicts @EternoSeeker , kindly check

**Pull request closed without merging**
