### PR TITLE
Change or Improve Buttons

### PR DESCRIPTION
**Pull request by KomalSrivastava**
#204

I have Improved Buttons by adding hover effect  of light orange in clear , random  and change grid size button .

## Description

**By adding hover effect  of light orange in clear , random  and change grid size button . when user move their pointer to these buttons then they experience a hover effect of light orange and the written things on those button will become BOLD and UNDERLINED which make it attractive..**

## Related Issue

 #204

## Checklist
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots (if necessary):

https://github.com/EternoSeeker/gameoflife/assets/132221203/b7b91f30-5732-4ba7-9c0f-9a415239ef67

### CODE REVIEW

**Comment by EternoSeeker** [comment]
it seems that you didn't sync your fork to the changes

**Comment by KomalSrivastava** [comment]
@EternoSeeker https://github.com/EternoSeeker/gameoflife/issues/204
I have Improved Buttons by adding hover effect of light orange in clear , random and change grid size button . i have created pull request in this but in adding logo i have just added the design of logo that i have made.

**Comment by EternoSeeker** [comment]
> @EternoSeeker #204 I have Improved Buttons by adding hover effect of light orange in clear , random and change grid size button . i have created pull request in this but in adding logo i have just added the design of logo that i have made
Alright but your changes have conflicts and your fork needs to be synced with the current main branch

**Comment by KomalSrivastava** [comment]
@EternoSeeker  I have forked this and added my changes i am not understanding what's wrong .. And the changes i have make in my vscode after fork and clone , all disappeared from there after i have pushed origin and create pull request . So for doing this again i have to make that changes again... How can i fix this...

**Comment by EternoSeeker** [comment]
your fork is a lot of commits behind, you had to keep it synced with the current main. now there are conflicts, it can't be merged until conflicts are resolved

**Comment by KomalSrivastava** [comment]
@EternoSeeker I have resolved the conflicts , kindly merge my issue. 

 My change look like this , you can  see in screen-recording below : -

https://github.com/EternoSeeker/gameoflife/assets/132221203/cf8f42c0-83de-4de7-a2f6-55834dfc5fdb

**Comment by EternoSeeker** [comment]
in the current state of the project, the buttons, if you hover over them, show their function, which I think is better.
also, there seem to be some problems with your fork, even tho conflicts are resolved with the sidebar code and some minor things don't seem to be the same.
I suggest you can work on the logo now

**Comment by KomalSrivastava** [comment]
@EternoSeeker SO what about this? The hover effect was there when i have my first PR but someone may changed between the interval of time in which i was resolving my issue.. If you want that hover effect i can add it back but i have worked in this project atleast merge this..

**Comment by EternoSeeker** [comment]
What you can do is, you have your code, you can create a new fork and try to apply/add that code freshly to the project's current state.

**Comment by KomalSrivastava** [comment]
@EternoSeeker i can do this but I can't create new fork 

Screenshot 2024-06-20 220914

**Comment by partha120804** [comment]
The buttons are already improved why are you trying to change it again !?

**Comment by EternoSeeker** [comment]
> The buttons are already improved why are you trying to change it again !?

It was a very old issue I think, and they didn't keep their fork synced

**Pull request closed without merging**
