### PR TITLE
Added Presets

### PR DESCRIPTION
**Pull request by Aryan-Shan**
Added New Presets

### CODE REVIEW

**Comment by EternoSeeker** [comment]
@Aryan-Shan in html file, presets are not named properly, please fix it, thank you.

**Comment by Aryan-Shan** [comment]
> @Aryan-Shan in html file, presets are not named properly, please fix it, thank you.

I have fixed the preset names as well.

**Comment by EternoSeeker** [comment]
Thank you. It was good contribution

**Comment by Aryan-Shan** [comment]
> Thank you. It was good contribution

Thanks a lot. It was a very interesting Project.

**Comment by Maheshwari-Love** [comment]
from where i can find the gifs of these newly added presets

**Pull request merged**
